### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by shion0104** [suwonkun/protospace-37110#1]
#URL
https://protospace-37110.herokuapp.com/

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されるようにしましょう**
「さん」が抜けているので修正しましょう。

- [x] **ログイン・ログアウトの状態に関わらず、プロトタイプ一覧を閲覧できるようにしましょう**
ログアウトの状態のときに閲覧できません。

- [x] **プロトタイプ詳細ページにて、ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・ キャッチコピー・コンセプト）が表示されるようにしましょう**
コンセプトが表示されていません。

- [x] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるようにしましょう**
以下のエラーページに遷移してしまいます。
<img width="547" alt="スクリーンショット 2021-11-02 16 09 17" src="https://user-images.githubusercontent.com/62644781/139801623-c6e4dbf0-f096-42f3-a5ac-f0ca8420d196.png">

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
①プロトタイプ詳細ページの投稿者名をクリックしたとき、トップページに遷移してしまいます。
②コメントの投稿者名をクリックしたとき、そのプロトタイプを投稿したユーザーの詳細ページに遷移してしまいます。

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるようにしましょう**
ユーザー名が表示されていません。
<img width="547" alt="スクリーンショット_2021-11-02_16_04_51" src="https://user-images.githubusercontent.com/62644781/139800981-ff0ed1db-14e6-4dd9-b8ae-2153eba2d4e1.png">

- [x] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できるようにしましょう**
トップページ・プロトタイプ詳細ページが閲覧できません。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by miyu-yamamoto** [comment]
@suwonkun さん、お待たせいたしました。
動作の確認をしたところ、修正が確認できませんでした。
マージやデプロイ忘れの可能性もありますので、改めてご確認をお願いします！

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、引き続き修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
コメントの投稿者名をクリックしたとき、そのプロトタイプを投稿したユーザーの詳細ページに遷移してしまいます。
<img width="587" alt="スクリーンショット_2021-11-03_11_25_55" src="https://user-images.githubusercontent.com/62644781/140002179-ff33f2a1-5776-4b78-9ddb-ee9e4fecb89e.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
ご提出ありがとうございます！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう！
